apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esdata-pvc
  namespace: elastic-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: azure-disk