apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elastic-stack

resources:
  - namespace.yaml
  - elasticsearch/deployment.yaml
  - elasticsearch/persistentvolumeclaim.yaml
  - elasticsearch/service.yaml
  - elasticsearch/storageclass.yaml
  - kibana/deployment.yaml
  - kibana/service.yaml
  - filebeat/serviceaccount.yaml
  - filebeat/role-kubeadm-config.yaml
  - filebeat/rolebinding-kubeadm-config.yaml
  - filebeat/configmap.yaml
  - filebeat/clusterrole.yaml
  - filebeat/clusterrolebinding.yaml
  - filebeat/role.yaml
  - filebeat/rolebinding.yaml
  - filebeat/daemonset.yaml